#ifndef __IOTIVITY_NODE_OC_CREATE_DELETE_RESOURCE_H__
#define __IOTIVITY_NODE_OC_CREATE_DELETE_RESOURCE_H__

#include <nan.h>

NAN_METHOD( bind_OCCreateResource );
NAN_METHOD( bind_OCDeleteResource );

#endif /* __IOTIVITY_NODE_OC_CREATE_DELETE_RESOURCE_H__ */
