#ifndef __IOTIVITY_NODE_OCSETDEFAULTDEVICEENTITYHANDLER_H__
#define __IOTIVITY_NODE_OCSETDEFAULTDEVICEENTITYHANDLER_H__

#include <nan.h>

NAN_METHOD(bind_OCSetDefaultDeviceEntityHandler);

#endif /* __IOTIVITY_NODE_OCSETDEFAULTDEVICEENTITYHANDLER_H__ */
